-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgClcpJY0Z5OMgcCox
dk+PiKrGVbsmPQ8lQYI0xqzYkC+gCgYIKoZIzj0DAQehRANCAARywR4onJWNVtIB
4ptFaJULpBaxJ6DF7lkE+40wMf24qfH5C6s8l1YYxrujm1gBPaQY4HYhxFf8pMGh
lhVWzxMo
-----END PRIVATE KEY-----